
package com.restService.service.ws.soap.branch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BranchInquirySoapInterface", targetNamespace = "http://branchInquiry.isc.co.ir/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BranchInquirySoapInterface {


    /**
     * 
     * @param baseDate
     * @param id
     * @return
     *     returns nahal.BranchArray
     */
    @WebMethod(operationName = "BranchInqServicesHttpSoap12Endpoint")
    @WebResult(partName = "return")
    @Action(input = "http://branchInquiry.isc.co.ir/BranchInquirySoapInterface/BranchInqServicesHttpSoap12EndpointRequest", output = "http://branchInquiry.isc.co.ir/BranchInquirySoapInterface/BranchInqServicesHttpSoap12EndpointResponse")
    BranchArray branchInqServicesHttpSoap12Endpoint(
            @WebParam(name = "baseDate", partName = "baseDate")
                    String baseDate,
            @WebParam(name = "id", partName = "id")
                    String id);

    /**
     * 
     * @param baseDate
     * @param id
     * @return
     *     returns nahal.BranchArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://branchInquiry.isc.co.ir/BranchInquirySoapInterface/getBranchesInfoRequest", output = "http://branchInquiry.isc.co.ir/BranchInquirySoapInterface/getBranchesInfoResponse")
    BranchArray getBranchesInfo(
            @WebParam(name = "baseDate", partName = "baseDate")
                    String baseDate,
            @WebParam(name = "id", partName = "id")
                    String id);

    /**
     * 
     * @param baseDate
     * @param id
     * @return
     *     returns nahal.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://branchInquiry.isc.co.ir/BranchInquirySoapInterface/getBranchesInfoStrRequest", output = "http://branchInquiry.isc.co.ir/BranchInquirySoapInterface/getBranchesInfoStrResponse")
    StringArray getBranchesInfoStr(
            @WebParam(name = "baseDate", partName = "baseDate")
                    String baseDate,
            @WebParam(name = "id", partName = "id")
                    String id);

}
